---
# web front-end
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "fb-user-filestore-api-{{ .Values.environmentName }}"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "fb-user-filestore-api-{{ .Values.environmentName }}"
        appGroup: "fb-user-filestore"
        fb-service-token-cache-access: "true"
        tier: "frontend"
    spec:
      serviceAccountName: "formbuilder-user-filestore-{{ .Values.environmentName }}"
      containers:
      - name: "fb-user-filestore-api-{{ .Values.environmentName }}"
        image: "926803513772.dkr.ecr.eu-west-1.amazonaws.com/formbuilder/fb-user-filestore-api:latest-{{ .Values.platformEnv }}"
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        # non-secret env vars
        # defined in config_map.yaml
        envFrom:
          - configMapRef:
              name: fb-user-filestore-api-env-{{ .Values.environmentName }}
        env:
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: fb-user-filestore-api-secrets-{{ .Values.environmentName }}
                key: secret_key_base
