apiVersion: v1
kind: Secret
metadata:
  name: fb-user-filestore-api-secrets-{{ .Values.environmentName }}
type: Opaque
data:
  secret_key_base: {{ .Values.secret_key_base }}
  key_encryption_iv: {{ .Values.key_encryption_iv }}
